"""Source-level UI contracts for Phase 0 surfaces without adding a JS test dependency."""

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]


def _read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def test_result_trust_panel_declares_all_required_fields() -> None:
    source = _read("apps/frontend/src/components/trust/ResultTrustPanel.tsx")
    required_tokens = {
        "Result type",
        "Evidence category",
        "Backend",
        "Simulator / hardware",
        "Status",
        "Estimate level",
        "Hardware horizon",
        "Qubits",
        "Circuit depth",
        "1Q gates",
        "2Q gates",
        "Shots",
        "Ideal / noisy",
        "Noise model",
        "Baseline",
        "Contract validity",
        "Verdict",
        "Confidence",
        "Time horizon",
        "Trust labels",
        "Assumptions",
        "Missing evidence",
        "Caveats",
        "Provenance",
        "Generated by",
        "Evidence source",
        "Source type",
        "Organization",
        "Published",
        "Last verified",
        "Vendor Reported",
        "Independently Reproduced",
        "not QCVV or hardware characterization",
    }
    assert all(token in source for token in required_tokens)


def test_result_trust_panel_is_used_on_required_routes() -> None:
    for relative_path in [
        "apps/frontend/src/app/assess/page.tsx",
        "apps/frontend/src/app/build/page.tsx",
        "apps/frontend/src/app/map/page.tsx",
        "apps/frontend/src/app/sessions/SessionsClient.tsx",
    ]:
        assert "ResultTrustPanel" in _read(relative_path), relative_path


def test_build_modes_and_pqc_no_circuit_copy_are_explicit() -> None:
    source = _read("apps/frontend/src/app/build/page.tsx")
    assert "Tutorial mode" in source
    assert "Contract mode" in source
    assert "Contract mode blocked" in source
    assert "Tutorial / Toy Simulation" in source
    assert "Legacy preview score" not in source
    assert "story.assessment.verdict" not in source
    assert "not a business recommendation" in source
    assert "does not create a quantum circuit" in source


def test_public_homepage_and_about_keep_independent_project_disclaimer() -> None:
    homepage = _read("apps/frontend/src/app/page.tsx")
    about = _read("apps/frontend/src/app/about/page.tsx")
    disclaimer = "not an official google product"

    assert disclaimer in homepage.lower()
    assert disclaimer in about.lower()
    assert "Explore the series" in homepage
    assert "Explore the software stack" in homepage
    assert "Start an assessment" in homepage
    assert "Core quantum concepts" in homepage
    assert "Beyond the Quantum Processor" in homepage
    assert '"use client"' not in homepage


def test_all_current_route_entry_files_still_exist() -> None:
    required_routes = [
        "apps/frontend/src/app/page.tsx",
        "apps/frontend/src/app/learn/page.tsx",
        "apps/frontend/src/app/learn/quantum-software-stack/page.tsx",
        "apps/frontend/src/app/series/page.tsx",
        "apps/frontend/src/app/series/[slug]/page.tsx",
        "apps/frontend/src/app/explore/page.tsx",
        "apps/frontend/src/app/assess/page.tsx",
        "apps/frontend/src/app/build/page.tsx",
        "apps/frontend/src/app/map/page.tsx",
        "apps/frontend/src/app/projects/page.tsx",
        "apps/frontend/src/app/sessions/page.tsx",
        "apps/frontend/src/app/jobs/page.tsx",
        "apps/frontend/src/app/about/page.tsx",
        "apps/frontend/src/app/use-cases/[slug]/page.tsx",
    ]
    assert all((REPO_ROOT / route).is_file() for route in required_routes)
