options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _AR_REPOSITORY: quantum-foundry
  _FRONTEND_SERVICE: quantum-foundry-frontend
  _BACKEND_SERVICE: quantum-foundry-backend

steps:
  - name: gcr.io/cloud-builders/docker
    id: build-backend
    args:
      - build
      - -f
      - apps/backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_BACKEND_SERVICE}:latest
      - apps/backend

  - name: gcr.io/cloud-builders/docker
    id: push-backend
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_BACKEND_SERVICE}:latest

  - name: gcr.io/cloud-builders/docker
    id: build-frontend
    args:
      - build
      - -f
      - apps/frontend/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://quantum-foundry-backend-271301686744.us-central1.run.app
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_FRONTEND_SERVICE}:latest
      - apps/frontend

  - name: gcr.io/cloud-builders/docker
    id: push-frontend
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPOSITORY}/${_FRONTEND_SERVICE}:latest
